### ISSUE TITLE
QGIS 3.30+

### ISSUE THREAD

**Issue by desertwolf7** [nextgis/qgis_headless#2]
В QGIS версии 3.30+ изменилось API в части определения типов, в связи с чем компиляция части, написанной на c++ завершается с ошибкой. 
Кроме того компиляторы в настоящее время пошли слишком умные, и обнаружив, что функция, которая обязательно должна возращать значение, теоретически может его не вернуть, завершают работу с ошибкой. Это относится к функциям HeadlessRender::layerGeometryTypeToQgsWkbType и HeadlessRender::layerAttributeTypetoQVariantType в файле utils.cpp.

Я подправил немного код, все изменения в приложенном diff файле. Может пригодится когда-нибудь.
С версией QGIS 3.34.3 все работает (ОС Alt Linux Server 10.2).

[qgis330.patch.diff.log](https://github.com/nextgis/qgis_headless/files/14229350/qgis330.patch.diff.log)

**Comment by dezhin** [comment]
Здравствуйте, не могли бы вы сделать пул-реквест?

**Comment by dezhin** [comment]
Спасибо, PR смержили.
